"Filed out from Dolphin Smalltalk 7"!

PPEpsilonParser subclass: #PPSentinel
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: 'current instance'!
PPSentinel guid: (GUID fromString: '{b64fc348-6168-4c29-b239-04f3d06e6b14}')!
PPSentinel comment: ''!
!PPSentinel categoriesForClass!Unclassified! !
!PPSentinel class methodsFor!

instance
	^ instance ifNil: [ instance := self new ]! !
!PPSentinel class categoriesFor: #instance!instance creation!public! !

