"Filed out from Dolphin Smalltalk 7"!

PPDelegateParser subclass: #PPEndOfInputParser
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PPEndOfInputParser guid: (GUID fromString: '{d79174e5-5166-457d-8a34-f7b020bd2727}')!
PPEndOfInputParser comment: ''!
!PPEndOfInputParser categoriesForClass!Unclassified! !
!PPEndOfInputParser methodsFor!

end
	^ self! !
!PPEndOfInputParser categoriesFor: #end!operators!public! !

