"Filed out from Dolphin Smalltalk 7"!

PPParser subclass: #PPEpsilonParser
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
PPEpsilonParser guid: (GUID fromString: '{1bd2086d-53b8-42d2-861c-aee0ac44a736}')!
PPEpsilonParser comment: ''!
!PPEpsilonParser categoriesForClass!Unclassified! !
!PPEpsilonParser methodsFor!

isNullable
	^ true!

parseOn: aStream
	^ nil! !
!PPEpsilonParser categoriesFor: #isNullable!*petitanalyzer-testing!public! !
!PPEpsilonParser categoriesFor: #parseOn:!parsing!public! !

